export interface Indicator {
    _id:string,
    idCourseStudent:string,
    student:string,
    course:string,
    numVideos:string,
    numContenido:string,
    numForos:string,
    numExamenes: string,
    numSesiones: string,
    numSesionesDif: string,
    numVideosDiferentes: string,
    timeExam: string,
    timeVideos:string,
    timeOthers:string,
}